name: Run all checks

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: node --version 
      - uses: actions/checkout@v3
      - run: npm --version
      - run: npm install
      - run: npm start
