name: Run all checks

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sample test
        run: echo "hello world"
